#ifndef _WAR_BasisTranscodeDefines_h_
#define _WAR_BasisTranscodeDefines_h_

#include "WAR_CompressedTexturePlatform.h"

#define BASISD_SUPPORT_UASTC            1
#define BASISD_SUPPORT_DXT1             WAR_TEXFMT_INCLUDE_DXT1
#define BASISD_SUPPORT_DXT5A            WAR_TEXFMT_INCLUDE_DXT5A
#define BASISD_SUPPORT_BC7              WAR_TEXFMT_INCLUDE_BC7
#define BASISD_SUPPORT_BC7_MODE5        WAR_TEXFMT_INCLUDE_BC7_MODE5
#define BASISD_SUPPORT_PVRTC1           WAR_TEXFMT_INCLUDE_PVRTC1
#define BASISD_SUPPORT_ETC2_EAC_A8      WAR_TEXFMT_INCLUDE_ETC2_EAC_A8
#define BASISD_SUPPORT_ASTC             WAR_TEXFMT_INCLUDE_ASTC
#define BASISD_SUPPORT_ATC              WAR_TEXFMT_INCLUDE_ATC
#define BASISD_SUPPORT_ASTC_HIGHER_OPAQUE_QUALITY   WAR_TEXFMT_INCLUDE_ASTC_HIGHER_OPAQUE_QUALITY
#define BASISD_SUPPORT_ETC2_EAC_RG11    WAR_TEXFMT_INCLUDE_ETC2_EAC_RG11
#define BASISD_SUPPORT_FXT1             WAR_TEXFMT_INCLUDE_FXT1
#define BASISD_SUPPORT_PVRTC2           WAR_TEXFMT_INCLUDE_PVRTC2

#endif // _WAR_BasisTranscodeDefines_h_
